sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t mirceanealcos/docker-ci-cd-test -f Dockerfile.dev .

script:
  - docker run -e CI=true mirceanealcos/docker-ci-cd-test npm run test